
>>> from course.models import Section
>>> s = Section.objects.get(id=1)
>>> s.all_students()
[<User: Course_Manager>, <User: Root>, <User: System>, <User: qiu58@purdue.edu>]
>>> sys = s.all_students()[3]
>>> sys.student.remove(sys)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'User' object has no attribute 'student'
>>> sys.student.remove([sys])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'User' object has no attribute 'student'
>>> s.student.remove([sys])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 988, in remove
    self._remove_items(self.source_field_name, self.target_field_name, *objs)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 1121, in _remove_items
    old_ids.add(obj)
TypeError: unhashable type: 'list'
>>> sys
<User: qiu58@purdue.edu>
>>> s.student.remove([sys])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 988, in remove
    self._remove_items(self.source_field_name, self.target_field_name, *objs)
  File "/Library/Python/2.7/site-packages/django/db/models/fields/related.py", line 1121, in _remove_items
    old_ids.add(obj)
TypeError: unhashable type: 'list'
>>> s.remove_students.remove([sys])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'function' object has no attribute 'remove'
>>> s.remove_students([sys])
>>> s.all_students()
[<User: Course_Manager>, <User: Root>, <User: System>]
>>> sys
<User: qiu58@purdue.edu>
>>> s.section_student_search(sys)
False
>>> s.section_student_search(s.all_students()[0])
True





from source.time_ult import fn_timer
    @fn_timer



import sys; print('Python %s on %s' % (sys.version, sys.platform))
import django; print('Django %s' % django.get_version())
sys.path.extend(['/Users/tianqiu/Desktop/WebProgramming/django/ece264site', '/Applications/PyCharm.app/Contents/helpers/pycharm', '/Applications/PyCharm.app/Contents/helpers/pydev'])
if 'setup' in dir(django): django.setup()
import django_manage_shell; django_manage_shell.run("/Users/tianqiu/Desktop/WebProgramming/django/ece264site")
Python 2.7.10 (default, Oct 23 2015, 19:19:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Django 1.8
/Applications/PyCharm.app/Contents/helpers/pydev/pydev_import_hook.py:21: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
  module = self._system_import(name, *args, **kwargs)

>>> from course.models import Course
>>> c.all_search(c.all_students()[0])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'c' is not defined
>>> c = Course.objects.get()
>>> c.all_search(c.all_students()[0])
True
>>> from django.contrib.auth.models import User
>>> user =  User.objects.get()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/django/db/models/query.py", line 338, in get
    (self.model._meta.object_name, num)
MultipleObjectsReturned: get() returned more than one User -- it returned 4!
>>> user =  User.objects.get(id = 4)
>>> user
<User: qiu58@purdue.edu>
>>> c.all_section()
[<Section: Spring 2016 ECE264-1>]
>>> c.all_section()[0]
<Section: Spring 2016 ECE264-1>
>>> c.all_section()[0].add_holders(user)
>>> c.all_search(user)
False
